Fiap.Exemplo01.MVC/Fiap.Exemplo01.MVC/Models/Aluno.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo01.MVC.Models
{
    public class Aluno
    {
        public string Nome { get; set; }
        public DateTime DataNascimento { get; set; }
        public decimal Salario { get; set; }
    }
}

Fiap.Exemplo01.MVC/Fiap.Exemplo01.MVC/Controllers/AlunoController.cs
using Fiap.Exemplo01.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo01.MVC.Controllers
{
    public class AlunoController : Controller
    {
        // GET: Aluno
        //Action para abrir o formulário
        [HttpGet]
        public ActionResult Cadastro()
        {
            return View();
        }

        //Action para cadastrar as informações do formulário
        [HttpPost]
        public ActionResult Salvar(Aluno aluno)
        {
            //Viewbag não é mantido após o redirect
            ViewBag.nomeAluno = aluno.Nome;
            ViewBag.dataAluno = aluno.DataNascimento;
            ViewBag.salarioAluno = aluno.Salario;

            //Tempdata é mantido após o redirect
            TempData["mensagem"] = "Aluno Registrado!";
            return View(aluno);
            //return Content("Gravou!" + aluno.Nome + " - " + aluno.DataNascimento.ToString("dd/MM/yyyy") + " - " + aluno.Salario); //Texto
        }
    }
}

Fiap.Exemplo01.MVC/Fiap.Exemplo01.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo01.MVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Fiap.Exemplo01.MVC/Fiap.Exemplo01.MVC/Views/Aluno/Cadastro.cshtml
@{
    ViewBag.Title = "Cadastro";
}

<h2>Cadastro</h2>

<form method="POST" action="~/Aluno/Salvar">
    <div class="form-group">
        <label for="nome">Nome: </label>
        <input class="form-control" type="text" name="nome" id="nome" />
    </div>
    <div class="form-group">
        <label for="dataNascimento">Data de Nascimento</label>
        <input class="form-control" type="date" name="dataNascimento" id="dataNascimento" placeholder="dd/mm/aaaa"/>
    </div>
    <div class="form-group">
        <label for="salario">Salário</label>
        <input class="form-control" type="number" name="salario" id="salario" placeholder="Ex.12345"/>
    </div>
    <div class="form-group">
        <input type="submit" value="Salvar" class="btn btn-default" />
    </div>
</form>

Fiap.Exemplo01.MVC/Fiap.Exemplo01.MVC/Views/Aluno/Salvar.cshtml
@model Fiap.Exemplo01.MVC.Models.Aluno

@{
    ViewBag.Title = "Salvar";
}
Usando o viewbag 
<br />
<h2>Salvar</h2>
<h3>@ViewBag.nomeAluno</h3>
<h3>@ViewBag.dataAluno</h3>
<h3>@ViewBag.salarioAluno</h3>

<br />
Usando o tempdata
<h3>Temp data: @TempData["mensagem"]</h3>

<br />
Usando o model
<h3>@Model.Nome</h3>
<h3>@Model.DataNascimento</h3>
<h3>@Model.Salario</h3>

Fiap.Exemplo01.MVC/Fiap.Exemplo01.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Fiap.Exemplo01.MVC/Fiap.Exemplo01.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cadastro de Aluno MVC</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Cadastro de Aluno", "Cadastro", "Aluno", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>